services:
  hub:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.local
    environment:
      SQLITE_DB_FILE: /data/hub.sqlite3
    volumes:
      - hub-sqlite:/data
    ports:
      - "${PORT:-3000}:3000"
    restart: unless-stopped

volumes:
  hub-sqlite:
